# Generated by Django 2.1.2 on 2018-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
